<?php

namespace Database\Seeders;

use App\Models\Animal;
use App\Models\Category;
use Illuminate\Database\Seeder;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Pastikan ada kategori hewan
        $kucingCategory = Category::firstOrCreate(['nama' => 'Kucing', 'tipe' => 'hewan']);
        $anjingCategory = Category::firstOrCreate(['nama' => 'Anjing', 'tipe' => 'hewan']);
        $kelinciCategory = Category::firstOrCreate(['nama' => 'Kelinci', 'tipe' => 'hewan']);
        $hamsterCategory = Category::firstOrCreate(['nama' => 'Hamster', 'tipe' => 'hewan']);
        $burungCategory = Category::firstOrCreate(['nama' => 'Burung', 'tipe' => 'hewan']);
        $ikanCategory = Category::firstOrCreate(['nama' => 'Ikan Hias', 'tipe' => 'hewan']);

        $animals = [
            [
                'nama' => 'Milo (Persia)',
                'umur' => 12,
                'category_id' => $kucingCategory->id,
                'deskripsi' => 'Kucing persia asli yang sangat lucu dan lincah. Sudah divaksin lengkap dan rutin pemeriksaan dokter hewan.',
                'harga' => 1500000,
                'stok' => 1,
                'isFavorite' => true,
                'photo' => 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => true,
                'asal_hewan' => 'lokal',
                'berat' => 4.5,
            ],
            [
                'nama' => 'Bella (Beagle)',
                'umur' => 6,
                'category_id' => $anjingCategory->id,
                'deskripsi' => 'Anjing jenis beagle yang sangat aktif dan ramah. Cocok untuk diajak bermain dan penjaga rumah.',
                'harga' => 2500000,
                'stok' => 2,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'betina',
                'sudah_steril' => false,
                'asal_hewan' => 'hasil_breeding',
                'berat' => 12.0,
            ],
            [
                'nama' => 'Luna (Scottish Fold)',
                'umur' => 8,
                'category_id' => $kucingCategory->id,
                'deskripsi' => 'Scottish fold betina dengan warna abu-abu solid. Karakternya sangat tenang dan manja.',
                'harga' => 3000000,
                'stok' => 1,
                'isFavorite' => true,
                'photo' => 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'betina',
                'sudah_steril' => false,
                'asal_hewan' => 'impor',
                'berat' => 3.8,
            ],
            [
                'nama' => 'Oliver (Angora)',
                'umur' => 10,
                'category_id' => $kucingCategory->id,
                'deskripsi' => 'Kucing Angora putih bersih dengan mata biru. Sangat anggun dan suka dielus.',
                'harga' => 1800000,
                'stok' => 1,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1513245543132-31f507417b26?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => true,
                'asal_hewan' => 'lokal',
                'berat' => 4.2,
            ],
            [
                'nama' => 'Max (Golden Retriever)',
                'umur' => 24,
                'category_id' => $anjingCategory->id,
                'deskripsi' => 'Golden Retriever yang cerdas dan patuh. Sangat baik dengan anak-anak.',
                'harga' => 4500000,
                'stok' => 1,
                'isFavorite' => true,
                'photo' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => false,
                'asal_hewan' => 'hasil_breeding',
                'berat' => 25.5,
            ],
            [
                'nama' => 'Coco (Rex Rabbit)',
                'umur' => 5,
                'category_id' => $kelinciCategory->id,
                'deskripsi' => 'Kelinci Rex dengan bulu halus seperti beludru. Sangat jinak dan suka makan wortel.',
                'harga' => 800000,
                'stok' => 3,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'betina',
                'sudah_steril' => false,
                'asal_hewan' => 'lokal',
                'berat' => 2.1,
            ],
            [
                'nama' => 'Simba (Maine Coon)',
                'umur' => 18,
                'category_id' => $kucingCategory->id,
                'deskripsi' => 'Kucing Maine Coon bertubuh besar dengan bulu tebal. Karakter tenang dan berwibawa.',
                'harga' => 5500000,
                'stok' => 1,
                'isFavorite' => true,
                'photo' => 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => true,
                'asal_hewan' => 'impor',
                'berat' => 7.5,
            ],
            [
                'nama' => 'Daisy (Pomeranian)',
                'umur' => 14,
                'category_id' => $anjingCategory->id,
                'deskripsi' => 'Anjing Pomeranian mungil yang aktif dan berisik. Sangat waspada terhadap orang asing.',
                'harga' => 3200000,
                'stok' => 2,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'betina',
                'sudah_steril' => true,
                'asal_hewan' => 'lokal',
                'berat' => 2.5,
            ],
            [
                'nama' => 'Snowy (Angora Kelinci)',
                'umur' => 7,
                'category_id' => $kelinciCategory->id,
                'deskripsi' => 'Kelinci Angora dengan bulu putih panjang yang sangat lebat. Memerlukan perawatan bulu rutin.',
                'harga' => 1200000,
                'stok' => 1,
                'isFavorite' => true,
                'photo' => 'https://images.unsplash.com/photo-1591384050534-738914dad5ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => false,
                'asal_hewan' => 'hasil_breeding',
                'berat' => 2.8,
            ],
            [
                'nama' => 'Hamtaro (Syrian Hamster)',
                'umur' => 3,
                'category_id' => $hamsterCategory->id,
                'deskripsi' => 'Hamster Syrian yang aktif bermain di malam hari. Kondisi sehat dan nafsu makan baik.',
                'harga' => 150000,
                'stok' => 10,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1548546738-8509cb246ed3?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => false,
                'asal_hewan' => 'lokal',
                'berat' => 0.15,
            ],
            [
                'nama' => 'Rio (Blue Gold Macaw)',
                'umur' => 36,
                'category_id' => $burungCategory->id,
                'deskripsi' => 'Burung Macaw dengan warna bulu indah. Sudah bisa mengucapkan beberapa kata sederhana.',
                'harga' => 15000000,
                'stok' => 1,
                'isFavorite' => true,
                'photo' => 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => false,
                'asal_hewan' => 'impor',
                'berat' => 1.1,
            ],
            [
                'nama' => 'Goldie (Oranda Goldfish)',
                'umur' => 4,
                'category_id' => $ikanCategory->id,
                'deskripsi' => 'Ikan Mas Koki Oranda dengan jambul merah yang cantik. Sangat lincah di akuarium.',
                'harga' => 250000,
                'stok' => 5,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'betina',
                'sudah_steril' => false,
                'asal_hewan' => 'lokal',
                'berat' => 0.2,
            ],
            [
                'nama' => 'Cooper (Corgi)',
                'umur' => 12,
                'category_id' => $anjingCategory->id,
                'deskripsi' => 'Pembroke Welsh Corgi yang sangat lincah dan menggemaskan. Sudah terlatih perintah dasar.',
                'harga' => 8500000,
                'stok' => 1,
                'isFavorite' => true,
                'photo' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => true,
                'asal_hewan' => 'impor',
                'berat' => 11.0,
            ],
            [
                'nama' => 'Nala (British Shorthair)',
                'umur' => 9,
                'category_id' => $kucingCategory->id,
                'deskripsi' => 'British Shorthair dengan bulu abu-abu padat. Karakternya tenang dan mandiri.',
                'harga' => 4500000,
                'stok' => 1,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1533743983669-94fa5c4333ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'betina',
                'sudah_steril' => true,
                'asal_hewan' => 'impor',
                'berat' => 4.8,
            ],
            [
                'nama' => 'Sparky (Sugar Glider)',
                'umur' => 6,
                'category_id' => $hamsterCategory->id,
                'deskripsi' => 'Sugar glider yang sudah jinak total (bonding). Sangat suka bermain di luar pouch.',
                'harga' => 450000,
                'stok' => 2,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1591142502690-34863ffb9c79?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => false,
                'asal_hewan' => 'lokal',
                'berat' => 0.12,
            ],
            [
                'nama' => 'Bobi (Kelinci Netherland Dwarf)',
                'umur' => 4,
                'category_id' => $kelinciCategory->id,
                'deskripsi' => 'Kelinci hias terkecil di dunia. Ukuran tubuh tetap imut meskipun sudah dewasa.',
                'harga' => 1500000,
                'stok' => 2,
                'isFavorite' => true,
                'photo' => 'https://images.unsplash.com/photo-1591384050534-738914dad5ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => false,
                'asal_hewan' => 'impor',
                'berat' => 0.9,
            ],
            [
                'nama' => 'Pipit (Lovebird)',
                'umur' => 12,
                'category_id' => $burungCategory->id,
                'deskripsi' => 'Burung Lovebird dengan warna sayap yang cerah. Sangat aktif berkicau.',
                'harga' => 350000,
                'stok' => 4,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1522850949506-58555ed7f748?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'betina',
                'sudah_steril' => false,
                'asal_hewan' => 'lokal',
                'berat' => 0.05,
            ],
            [
                'nama' => 'Bruno (Bulldog)',
                'umur' => 20,
                'category_id' => $anjingCategory->id,
                'deskripsi' => 'English Bulldog yang tenang dan setia. Sangat suka tidur dan malas-malasan.',
                'harga' => 7000000,
                'stok' => 1,
                'isFavorite' => false,
                'photo' => 'https://images.unsplash.com/photo-1512540315028-2c1a6497da04?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'jenis_kelamin' => 'jantan',
                'sudah_steril' => true,
                'asal_hewan' => 'impor',
                'berat' => 22.0,
            ],
        ];

        foreach ($animals as $animalData) {
            $animal = Animal::create($animalData);

            // Buat dummy galeri
            $galleryPhotos = [
                'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
                'https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
            ];

            foreach ($galleryPhotos as $photo) {
                \App\Models\FotoHewan::create([
                    'hewan_id' => $animal->id,
                    'path_foto' => $photo,
                ]);
            }
        }
    }
}
