<?php

return [
    [
        'name' => 'Kucing Persia Peaknose',
        'category' => 'Kucing',
        'age' => '3 Bulan',
        'description' => 'Kucing persia dengan hidung pesek yang menggemaskan, bulu lebat dan sifat manja. Sudah divaksin dan obat cacing.',
        'price' => 4500000,
        'status' => 'Siap Adopsi',
        'isTopSale' => true,
        'image' => 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=800',
    ],
    [
        'name' => 'Siberian Husky',
        'category' => 'Anjing',
        'age' => '5 Bulan',
        'description' => 'Anjing husky yang energik dan cerdas dengan mata biru cerah. Cocok untuk keluarga aktif dan memiliki halaman luas.',
        'price' => 6000000,
        'status' => 'Siap Adopsi',
        'isTopSale' => true,
        'image' => 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?auto=format&fit=crop&q=80&w=800',
    ],
    [
        'name' => 'Burung Macaw Biru',
        'category' => 'Burung',
        'age' => '1 Tahun',
        'description' => 'Burung eksotis yang cerdas dan bisa meniru suara manusia. Sangat aktif dan membutuhkan perhatian khusus.',
        'price' => 8500000,
        'status' => 'Tersedia: 1',
        'isTopSale' => true,
        'image' => '/img/hewan/burung-macau.jpg',
    ],
    [
        'name' => 'Kelinci Anggora',
        'category' => 'Kelinci',
        'age' => '4 Bulan',
        'description' => 'Kelinci berbulu super tebal dan lembut, cocok sebagai hewan peliharaan indoor yang tenang dan lucu.',
        'price' => 850000,
        'status' => 'Tersedia: 3',
        'isTopSale' => true,
        'image' => '/img/hewan/kelinci.jpg',
    ],
    [
        'name' => 'British Shorthair',
        'category' => 'Kucing',
        'age' => '6 Bulan',
        'description' => 'Kucing BSH dengan warna abu-abu kebiruan yang khas, sifat tenang dan sangat penyayang. Keturunan ras asli.',
        'price: ' . 5500000,
        'status' => 'Siap Adopsi',
        'isTopSale' => true,
        'image' => '/img/hewan/kucing.jpg',
    ],
];
